### PR TITLE
Parse template tag for generics

### LINKED ISSUE #1442: ide-helper:generate output has wrong return type for Cache::get?
### Versions:
- ide-helper Version: 2.13.0
- Laravel Version: 9.52.7 
- PHP Version: 8.0.28

### Description:
The generated _ide_helper.php file has the wrong return type for the Cache::get function, here is what is generated:

```
                    /**
         * Retrieve an item from the cache by key.
         *
         * @template TCacheValue
         * @param array|string $key
         * @param \Illuminate\Cache\TCacheValue|\Illuminate\Cache\(\Closure():  TCacheValue)  $default
         * @return \Illuminate\Cache\(TCacheValue is null ? mixed : TCacheValue)
         * @static 
         */ 
        public static function get($key, $default = null)
        {
                        /** @var \Illuminate\Cache\Repository $instance */
                        return $instance->get($key, $default);
        }
```

The function declaration on the cache facade says it's return type should be mixed https://github.com/laravel/framework/blob/9.x/src/Illuminate/Support/Facades/Cache.php#L17

### PR DESCRIPTION
**Pull request by chack1172**
This fixes https://github.com/barryvdh/laravel-ide-helper/issues/1442

### CODE REVIEW

**Comment by barryvdh** [comment]
Thanks, but tests seem to be failing. Any ideas?

**Comment by chack1172** [comment]
@barryvdh there was an issue with PHP 7. Fixed.

**Comment by chack1172** [comment]
@barryvdh sorry for the varius commits. I only have 7.3 installed on my pc, so I don't get 7.2 issues instantly

**Comment by barryvdh** [comment]
Thanks!

**Comment by ayrtonandino** [comment]
Does this also fixes things like `Illuminate\Auth\Access\iterable`, `Illuminate\Cache\array`, `Illuminate\Database\Eloquent\static`?

Same problem as generics, but for phpdoc types.

**Comment by chack1172** [comment]
@ayrtonandino no, this only fixes templates used in phpdoc method. This is also not fixing templates used in class phpdoc, I'll make a another PR for that.

**Pull request merged**
